name: qudailiyu

on:
  workflow_dispatch:
  schedule:
    - cron: '47 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qudailiyu
        env:
          h683: ${{ secrets.h683 }}
        run: |
          echo $h683 | jq -r .durch056 | /bin/bash
          echo $txeve7441 | jq -r .zpgb5825 | /bin/bash
          echo $m0 | jq -r .feadd6 | /bin/bash

